spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.ysling.shopflow.core:  DEBUG